services:
  mysql-db-system:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=demosql'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  phpmyadmin:
    image: 'phpmyadmin:latest'
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql-db-system
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'PMA_HOST=mysql'
      - 'PMA_PORT=3306'
