services:
# Sql is an instance of service
  db:
    image: mysql:latest
    container_name: mysql-db-demo-security
    # Load environment variable from file
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      # Use port 3305 for avoid conflict with mysql in main machine
      - "3305:3306"
    # (restart: unless-stop)
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    env_file: .env
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
  app:
    # Specific that this service is build not image and choose folder
    # backend as folder container Dockerfile
    build: ./backend
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

    # TODO: use application property from env variable instead
    # Mark not run this docker right now - i prefer run on intellij for
    # debug break point
    profiles:
      - donotstart

